version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////data/sqlite_user.db  # Use SQLite and a path within the volume
    ports:
      - "8001:8000"
    volumes:
      - user_data:/data  # Persistent volume for user service

  transaction-service:
    build:
      context: ./transaction-service
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////data/sqlite_transaction.db  # Use SQLite and a path within the volume
    ports:
      - "8002:8000"
    volumes:
      - transaction_data:/data  # Persistent volume for transaction service

  notification-service:
    build:
      context: ./notification-service
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////data/sqlite_notification.db  # Use SQLite and a path within the volume
    ports:
      - "8003:8000"
    volumes:
      - notification_data:/data  # Persistent volume for notification service

  donation-service:
    build:
      context: ./donation-service
    environment:
      - PYTHONPATH=/app
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_...}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-pk_test_...}
      - DONATION_SUCCESS_URL=${DONATION_SUCCESS_URL:-http://localhost:3000/success}
      - DONATION_CANCEL_URL=${DONATION_CANCEL_URL:-http://localhost:3000/cancel}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8004:8000"

  frontend:
    build:
      context: ./frontend  
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - transaction-service
      - notification-service
      - donation-service

volumes:
  user_data:  # Volume for user service data
  transaction_data:  # Volume for transaction service data
  notification_data:  # Volume for notification service data
