# ConfigMap for frontend environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  REACT_APP_USER_SERVICE_URL: 'http://34.118.8.17:8001'
  REACT_APP_TASK_SERVICE_URL: 'http://34.116.170.83:8002'
  REACT_APP_NOTIFICATION_SERVICE_URL: 'http://34.118.36.199:8003'
  REACT_APP_FIREBASE_API_KEY: 'your_api_key'
  REACT_APP_FIREBASE_AUTH_DOMAIN: 'your_project.firebaseapp.com'
  REACT_APP_FIREBASE_PROJECT_ID: 'your_project_id'
  REACT_APP_FIREBASE_APP_ID: 'your_app_id'

---
# Deployment for frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: europe-central2-docker.pkg.dev/ersms-25l-462511/ersms-app-test/frontend
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_USER_SERVICE_URL
            - name: REACT_APP_TASK_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_TASK_SERVICE_URL
            - name: REACT_APP_NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_NOTIFICATION_SERVICE_URL
            - name: REACT_APP_FIREBASE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_FIREBASE_API_KEY
            - name: REACT_APP_FIREBASE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_FIREBASE_AUTH_DOMAIN
            - name: REACT_APP_FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_FIREBASE_PROJECT_ID
            - name: REACT_APP_FIREBASE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_FIREBASE_APP_ID

---
# LoadBalancer Service for frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer # Use LoadBalancer to expose frontend to the internet
  ports:
    - port: 80 # External port
      targetPort: 3000 # Internal container port
  selector:
    app: frontend
