name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and push images
        run: |
          chmod +x build_and_push.sh
          ./build_and_push.sh frontend
          ./build_and_push.sh user-service
          ./build_and_push.sh task-service
          ./build_and_push.sh notification-service
          ./build_and_push.sh donation-service
