name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and push images
        run: |
          chmod +x build_and_push.sh
          ./build_and_push.sh frontend
          ./build_and_push.sh user-service
          ./build_and_push.sh task-service
          ./build_and_push.sh notification-service

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Deploy to GKE
        run: |
          kubectl apply -f gcp-iac/k8s_manifests/
          kubectl rollout status deployment/frontend --timeout=120s
          kubectl rollout status deployment/user-service --timeout=120s
          kubectl rollout status deployment/task-service --timeout=120s
          kubectl rollout status deployment/notification-service --timeout=120s
