name: Teardown Deployment

on:
  workflow_dispatch:

jobs:
  teardown:
    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: 'True'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          sed -i 's#/opt/homebrew/share/google-cloud-sdk/bin/gke-gcloud-auth-plugin#gke-gcloud-auth-plugin#' $HOME/.kube/config

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          curl -fsS https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Delete resources
        run: |
          kubectl delete -f gcp-iac/k8s_manifests/ --ignore-not-found
          kubectl delete pods --all --namespace default --ignore-not-found
